project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: '..'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  [
    {
      source: '/src/Themes/default/languages/LightPortal/LightPortal.english.php',
      dest: '/Themes/default/languages/LightPortal/LightPortal.english.php',
      translation: '%original_path%/LightPortal.%language%.php',
    },
    {
      source: '/src/Sources/LightPortal/Plugins/**/english.php',
      dest: '/Sources/LightPortal/Plugins/**/english.php',
      translation: '%original_path%/%language%.php',
    },
    {
      source: '/docs/.vitepress/config/en.js',
      translation: '/docs/.vitepress/config/%two_letters_code%.js',
    },
    {
      source: '/docs/src/en/**/*.*',
      translation: '/docs/src/%two_letters_code%/**/%original_file_name%',
    },
  ]
