project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: '..'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  [
    {
      source: '/src/Themes/default/languages/LightPortal/LightPortal.english.php',
      dest: '/Themes/default/languages/LightPortal/LightPortal.english.php',
      translation: '%original_path%/LightPortal.%language%.php',
    },
    {
      source: '/src/Sources/LightPortal/Plugins/**/english.php',
      dest: '/Sources/LightPortal/Plugins/**/english.php',
      translation: '%original_path%/%language%.php',
    },
    {
      source: '/docs/.vitepress/locales/en.js',
      translation: '/docs/.vitepress/locales/%two_letters_code%.js',
    },
    {
      source: '/docs/src/**/*',
      translation: '/docs/src/%two_letters_code%/**/%original_file_name%',
      ignore:
        [
          '/docs/src/public',
          '/docs/src/ar',
          '/docs/src/el',
          '/docs/src/da',
          '/docs/src/es',
          '/docs/src/es-mx',
          '/docs/src/it',
          '/docs/src/de',
          '/docs/src/nl',
          '/docs/src/no',
          '/docs/src/pl',
          '/docs/src/pt',
          '/docs/src/ru',
          '/docs/src/tr',
          '/docs/src/uk',
          '/docs/src/fr',
          '/docs/src/cs',
          '/docs/src/sv',
          '/docs/src/sl',
        ],
    },
  ]
