<?php

return [
	'title' => 'Chessboard',
	'description' => 'Provides an opportunity to play chess with the computer.',
	'engine_note' => 'The %s engine is used.',
	'board_style' => 'Board style',
	'piece_style' => 'Piece style',
	'border_type' => 'Border type',
	'marker_type' => 'Marker type',
	'skill_level' => 'Skill level',
	'depth' => 'Maximum search depth (in plies)',
	'thinking' => 'Computer is thinking...',
	'player_black' => 'White — computer, black — you',
	'player_white' => 'White — you, black — computer',
	'black_turn' => "Black's turn",
	'white_turn' => "White's turn",
	'check' => '— check!',
	'checkmate' => 'Checkmate!',
	'black_won' => 'Black won.',
	'white_won' => 'White won.',
	'game_draw' => 'Draw!',
	'game_over' => 'Game over.',
	'new_game' => 'New game',
];
