<?php

/**
 * @package Snowflakes (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023-2024 Bugo
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @category plugin
 * @version 13.11.24
 */

namespace Bugo\LightPortal\Plugins\Snowflakes;

use Bugo\Compat\Theme;
use Bugo\LightPortal\Plugins\Event;
use Bugo\LightPortal\Plugins\Plugin;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class Snowflakes extends Plugin
{
	public string $type = 'other';

	private array $params = [
		'icon_color'       => '#a6e7ff',
		'icon_size'        => 15,
		'snowflakes_count' => 100,
		'snowdrifts_count' => 10,
	];

	public function init(): void
	{
		Theme::loadCSSFile('light_portal/snowflakes/snow.min.css');

		Theme::loadJavaScriptFile('light_portal/snowflakes/Snow.min.js', ['minimize' => true]);

		Theme::addInlineJavaScript('
			new Snow({
				iconColor: "' . (empty($this->context['icon_color']) ? $this->params['icon_color'] : $this->context['icon_color']) . '",
				iconSize: ' . (empty($this->context['icon_size']) ? $this->params['icon_size'] : $this->context['icon_size']) . ',
				countSnowflake: ' . (empty($this->context['snowflakes_count']) ? $this->params['snowflakes_count'] : $this->context['snowflakes_count']) . ',
				showSnowBalls: ' . (empty($this->context['enable_snowdrifts']) ? 'false' : 'true') . ',
				snowBallsLength: ' . (empty($this->context['snowdrifts_count']) ? $this->params['snowdrifts_count'] : $this->context['snowdrifts_count']) . '
			});', true);
	}

	public function addSettings(Event $e): void
	{
		$this->addDefaultValues($this->params);

		$settings = &$e->args->settings;

		$settings[$this->name][] = ['color', 'icon_color'];
		$settings[$this->name][] = ['int', 'icon_size', 'min' => 1];
		$settings[$this->name][] = ['range', 'snowflakes_count'];
		$settings[$this->name][] = ['check', 'enable_snowdrifts'];
		$settings[$this->name][] = ['range', 'snowdrifts_count', 'max' => 10];
	}

	public function prepareAssets(Event $e): void
	{
		$e->args->assets['css'][$this->name][] = 'https://cdn.jsdelivr.net/gh/Alaev-Co/snowflakes/dist/snow.min.css';
		$e->args->assets['scripts'][$this->name][] = 'https://cdn.jsdelivr.net/gh/Alaev-Co/snowflakes/dist/Snow.min.js';
	}

	public function credits(Event $e): void
	{
		$e->args->links[] = [
			'title' => 'Snowflakes',
			'link' => 'https://github.com/Alaev-Co/snowflakes',
			'author' => 'Alaev & Co',
			'license' => [
				'name' => 'The MIT License',
				'link' => 'https://github.com/Alaev-Co/snowflakes?tab=readme-ov-file#MIT-1-ov-file'
			]
		];
	}
}
