<?php

/**
 * @package SimpleMenu (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021-2024 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category plugin
 * @version 05.11.24
 */

namespace Bugo\LightPortal\Plugins\SimpleMenu;

use Bugo\Compat\{Config, Lang, Utils};
use Bugo\LightPortal\Areas\Fields\CustomField;
use Bugo\LightPortal\Enums\Tab;
use Bugo\LightPortal\Plugins\Block;
use Bugo\LightPortal\Plugins\Event;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class SimpleMenu extends Block
{
	public string $icon = 'far fa-list-alt';

	public function prepareBlockParams(Event $e): void
	{
		if (Utils::$context['current_block']['type'] !== 'simple_menu')
			return;

		$e->args->params['items'] = '';
	}

	public function validateBlockParams(Event $e): void
	{
		if (Utils::$context['current_block']['type'] !== 'simple_menu')
			return;

		$data = $this->request()->only(['item_name', 'item_link']);

		$items = [];
		if ($data && isset($data['item_name']) && isset($data['item_link'])) {
			foreach ($data['item_name'] as $key => $item) {
				if (empty($link = $data['item_link'][$key]))
					continue;

				$items[] = [
					'name' => $item,
					'link' => $link,
				];
			}

			$this->request()->put('items', json_encode($items, JSON_UNESCAPED_UNICODE));
		}

		$e->args->params['items'] = FILTER_DEFAULT;
	}

	public function prepareBlockFields(): void
	{
		if (Utils::$context['current_block']['type'] !== 'simple_menu')
			return;

		CustomField::make('items', Lang::$txt['lp_simple_menu']['items'])
			->setTab(Tab::CONTENT)
			->setValue($this->getFromTemplate('simple_menu_items'));
	}

	public function getData(string $items): array
	{
		if (empty($items))
			return [];

		$html = '
		<ul class="dropmenu">';

		$items = Utils::jsonDecode($items, true);

		foreach ($items as $item) {
			[$title, $link] = [$item['name'], $item['link']];

			$ext = true;
			if (! str_starts_with((string) $link, 'http')) {
				$active = $link == Utils::$context['current_action'];
				$link   = Config::$scripturl . '?action=' . $link;
				$ext    = false;
			}

			$html .= '
			<li style="width: 100%">
				<a' . (empty($active) ? '' : ' class="active"') . ' href="' . $link . '"' . (empty($ext) ? '' : ' target="_blank" rel="noopener"') . '>
					<span>' . $title . '</span>
				</a>
			</li>';
		}

		$html .= '
		</ul>';

		return ['content' => $html];
	}

	public function prepareContent(Event $e): void
	{
		[$data, $parameters] = [$e->args->data, $e->args->parameters];

		if ($data->type !== 'simple_menu' || empty($parameters['items']))
			return;

		$html = $this->cache('simple_menu_addon_b' . $data->id)
			->setLifeTime($data->cacheTime)
			->setFallback(self::class, 'getData', $parameters['items']);

		if (empty($html))
			return;

		echo $html['content'] ?? '';
	}
}
