<?php

/**
 * KintDebugger.php
 *
 * @package KintDebugger (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023 Bugo
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @category addon
 * @version 24.05.23
 */

namespace Bugo\LightPortal\Addons\KintDebugger;

use Bugo\LightPortal\Addons\Plugin;
use Kint\Renderer\RichRenderer;
use Kint;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class KintDebugger extends Plugin
{
	public string $type = 'other';

	private array $themes = ['original.css', 'solarized.css', 'solarized-dark.css', 'aante-light.css'];

	public function init()
	{
		require_once __DIR__ . '/vendor/autoload.php';

		RichRenderer::$folder = empty($this->context['lp_kint_debugger_plugin']['show_top']);
		RichRenderer::$theme = $this->context['lp_kint_debugger_plugin']['theme'] ?? $this->themes[0];
		Kint::$expanded = empty($this->context['lp_kint_debugger_plugin']['expanded']) ? false : true;
		Kint::$aliases[] = 'dump';
	}

	public function addSettings(array &$config_vars)
	{
		$this->addDefaultValues([
			'theme' => 'original.css',
		]);

		$config_vars['kint_debugger'][] = ['title', 'help_title'];
		$config_vars['kint_debugger'][] = ['desc', 'commands'];
		$config_vars['kint_debugger'][] = ['check', 'show_top'];
		$config_vars['kint_debugger'][] = ['check', 'expanded'];
		$config_vars['kint_debugger'][] = ['select', 'theme', array_combine($this->themes, $this->getThemeList())];
	}

	public function credits(array &$links)
	{
		$links[] = [
			'title' => 'Kint',
			'link' => 'https://github.com/kint-php/kint',
			'author' => 'Jonathan Vollebregt, Rokas Šleinius',
			'license' => [
				'name' => 'the MIT License',
				'link' => 'https://github.com/kint-php/kint/blob/master/LICENSE'
			]
		];
	}

	private function getThemeList(): array
	{
		return array_map(fn($theme) => str_replace('.css', '', ucwords(str_replace('-', ' ', $theme))), $this->themes);
	}
}
