<?php

/**
 * MainMenu.php
 *
 * @package MainMenu (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021-2024 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category addon
 * @version 17.01.24
 */

namespace Bugo\LightPortal\Addons\MainMenu;

use Bugo\LightPortal\Addons\Plugin;
use Bugo\LightPortal\Utils\{Config, User, Utils};

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class MainMenu extends Plugin
{
	public string $type = 'other';

	public function init(): void
	{
		$this->applyHook('menu_buttons');
	}

	public function menuButtons(array &$buttons): void
	{
		$this->prepareVariables();

		if (! empty(Utils::$context['lp_main_menu_addon_portal_langs'][User::$info['language']]))
			$buttons[LP_ACTION]['title'] = Utils::$context['lp_main_menu_addon_portal_langs'][User::$info['language']];

		if (! empty(Utils::$context['lp_main_menu_addon_forum_langs'][User::$info['language']]))
			$buttons[empty(Config::$modSettings['lp_standalone_mode']) ? 'home' : 'forum']['title'] = Utils::$context['lp_main_menu_addon_forum_langs'][User::$info['language']];
	}

	public function frontLayouts(): void
	{
		if (! empty(Utils::$context['lp_main_menu_addon_portal_langs'][User::$info['language']]) && ! empty(Utils::$context['linktree'][1]))
			Utils::$context['linktree'][1]['name'] = Utils::$context['lp_main_menu_addon_portal_langs'][User::$info['language']];
	}

	public function addSettings(array &$config_vars): void
	{
		$config_vars['main_menu'][] = ['callback', 'items', $this->showList()];
	}

	public function showList(): bool|string
	{
		$this->prepareForumLanguages();

		$this->prepareVariables();

		$this->setTemplate();

		ob_start();

		callback_main_menu_table();

		return ob_get_clean();
	}

	public function saveSettings(array &$plugin_options): void
	{
		if (! isset($plugin_options['items']))
			return;

		$portal_langs = $forum_langs = [];

		if ($this->request()->has('portal_item_langs')) {
			foreach ($this->request('portal_item_langs') as $lang => $val) {
				if (! empty($val))
					$portal_langs[$lang] = $val;
			}
		}

		if ($this->request()->has('forum_item_langs')) {
			foreach ($this->request('forum_item_langs') as $lang => $val) {
				if (! empty($val))
					$forum_langs[$lang] = $val;
			}
		}

		$plugin_options['portal_langs'] = json_encode($portal_langs, JSON_UNESCAPED_UNICODE);
		$plugin_options['forum_langs']  = json_encode($forum_langs, JSON_UNESCAPED_UNICODE);
	}

	private function prepareVariables(): void
	{
		Utils::$context['lp_main_menu_addon_portal_langs'] = Utils::jsonDecode(Utils::$context['lp_main_menu_plugin']['portal_langs'] ?? '', true);
		Utils::$context['lp_main_menu_addon_forum_langs']  = Utils::jsonDecode(Utils::$context['lp_main_menu_plugin']['forum_langs'] ?? '', true);
	}
}
