<?php

return [
	'title' => 'Apex Charts',
	'description' => 'Easily and quickly add charts of any type to your forum.',
	'dark_themes' => 'Select themes for which the appearance of charts should be dark',
	'type' => 'Chart type',
	'type_set' => ['Line chart', 'Area chart', 'Column chart', 'Bar chart', 'Pie chart', 'Donut chart', 'Radial Bar chart', 'Polar Area chart'],
	'data' => 'Data (Y-axis)',
	'data_placeholder' => 'Example: 10, 20, 30, 40, 50',
	'set_name' => 'Name',
	'set_add' => 'Add set',
	'labels' => 'Labels (X-axis)',
	'labels_placeholder' => 'Example: Jan, Feb, Mar, Apr, May',
	'palette' => 'Palette of colors',
	'fill_type' => 'Fill type',
	'fill_type_set' => ['Solid', 'Gradient'],
	'fill_opacity' => 'Opacity of the fill',
	'stroke_curve' => 'Lines type',
	'stroke_curve_set' => ['Smooth lines', 'Straight lines', 'Step lines'],
	'labels_type' => 'Labels type',
	'labels_type_set' => ['Category', 'Datetime', 'Numeric'],
	'chart_title' => 'Title of chart',
	'chart_title_placeholder' => 'Text to display as a title of chart',
	'stacked' => 'Enable stacked bar charts',
	'stacked_after' => ' Stacked bar charts can be used to show how one data series is made up of a number of smaller pieces.',
	'full_stacked' => '100% stacked bar charts',
	'full_stacked_after' => 'The bars are stacked on top of each other based on their percentage or weightage among the groups.',
	'legend' => 'Show legend',
	'toolbar' => 'Display the toolbar / menu in the top right corner',
	'no_data' => 'There is no data yet',
	'exportToSVG' => 'Download SVG',
	'exportToPNG' => 'Download PNG',
	'exportToCSV' => 'Download CSV',
	'menu' => 'Menu',
	'selection' => 'Selection',
	'selectionZoom' => 'Selection Zoom',
	'zoomIn' => 'Zoom In',
	'zoomOut' => 'Zoom Out',
	'pan' => 'Panning',
	'reset' => 'Reset Zoom'
];
