<?php

/**
 * Snowflakes.php
 *
 * @package Snowflakes (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023 Bugo
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @category addon
 * @version 24.12.23
 */

namespace Bugo\LightPortal\Addons\Snowflakes;

use Bugo\LightPortal\Addons\Plugin;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class Snowflakes extends Plugin
{
	public string $type = 'other';

	private array $params = [
		'icon_color'       => '#a6e7ff',
		'icon_size'        => 15,
		'snowflakes_count' => 100,
		'snowdrifts_count' => 10,
	];

	public function init(): void
	{
		$this->loadCSSFile('light_portal/snowflakes/snow.min.css');
		$this->loadJavaScriptFile('light_portal/snowflakes/Snow.min.js', ['minimize' => true]);
		$this->addInlineJavaScript('
			new Snow({
				iconColor: "' . (empty($this->context['lp_snowflakes_plugin']['icon_color']) ? $this->params['icon_color'] : $this->context['lp_snowflakes_plugin']['icon_color']) . '",
				iconSize: ' . (empty($this->context['lp_snowflakes_plugin']['icon_size']) ? $this->params['icon_size'] : $this->context['lp_snowflakes_plugin']['icon_size']) . ',
				countSnowflake: ' . (empty($this->context['lp_snowflakes_plugin']['snowflakes_count']) ? $this->params['snowflakes_count'] : $this->context['lp_snowflakes_plugin']['snowflakes_count']) . ',
				showSnowBalls: ' . (empty($this->context['lp_snowflakes_plugin']['enable_snowdrifts']) ? 'false' : 'true') . ',
				snowBallsLength: ' . (empty($this->context['lp_snowflakes_plugin']['snowdrifts_count']) ? $this->params['snowdrifts_count'] : $this->context['lp_snowflakes_plugin']['snowdrifts_count']) . '
			});', true);
	}

	public function addSettings(array &$config_vars): void
	{
		$this->addDefaultValues($this->params);

		$config_vars['snowflakes'][] = ['color', 'icon_color'];
		$config_vars['snowflakes'][] = ['int', 'icon_size', 'min' => 1];
		$config_vars['snowflakes'][] = ['range', 'snowflakes_count'];
		$config_vars['snowflakes'][] = ['check', 'enable_snowdrifts'];
		$config_vars['snowflakes'][] = ['range', 'snowdrifts_count', 'max' => 10];
	}

	public function prepareAssets(array &$assets): void
	{
		$assets['css']['snowflakes'][]     = 'https://cdn.jsdelivr.net/gh/Alaev-Co/snowflakes/dist/snow.min.css';
		$assets['scripts']['snowflakes'][] = 'https://cdn.jsdelivr.net/gh/Alaev-Co/snowflakes/dist/Snow.min.js';
	}

	public function credits(array &$links): void
	{
		$links[] = [
			'title' => 'Snowflakes',
			'link' => 'https://github.com/Alaev-Co/snowflakes',
			'author' => 'Alaev & Co',
			'license' => [
				'name' => 'The MIT License',
				'link' => 'https://github.com/Alaev-Co/snowflakes?tab=readme-ov-file#MIT-1-ov-file'
			]
		];
	}
}
