<?php

/**
 * BootstrapIcons.php
 *
 * @package BootstrapIcons (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021-2022 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category addon
 * @version 09.01.22
 */

namespace Bugo\LightPortal\Addons\BootstrapIcons;

use Bugo\LightPortal\Addons\Plugin;

/**
 * Generated by Plugin Maker
 */
class BootstrapIcons extends Plugin
{
	public string $type = 'other';

	private string $prefix = 'bi bi-';

	public function init()
	{
		loadCSSFile('https://cdn.jsdelivr.net/npm/bootstrap-icons@1/font/bootstrap-icons.min.css', ['external' => true, 'seed' => false]);
	}

	public function addSettings(array &$config_vars)
	{
		$config_vars['bootstrap_icons'][] = ['check', 'replace_ui_icons'];
	}

	public function prepareIconList(array &$all_icons)
	{
		if (($icons = $this->cache()->get('all_bi_icons', LP_CACHE_TIME * 7)) === null) {
			$content = file_get_contents('https://raw.githubusercontent.com/twbs/icons/main/font/bootstrap-icons.json');
			$json = array_flip(json_decode($content, true));

			$icons = [];
			foreach ($json as $icon) {
				$icons[] = $this->prefix . $icon;
			}

			$this->cache()->put('all_bi_icons', $icons, LP_CACHE_TIME * 7);
		}

		$all_icons = array_merge($all_icons, $icons);
	}

	public function changeIconSet(array &$set)
	{
		if (empty($this->modSettings['lp_bootstrap_icons_addon_replace_ui_icons']))
			return;

		$set['home']        = 'house-door';
		$set['cog_spin']    = 'gear';
		$set['pager']       = 'inboxes';
		$set['sections']    = 'folder';
		$set['panels']      = 'columns-gap';
		$set['tools']       = 'tools';
		$set['info']        = 'exclamation-circle';
		$set['arrows']      = 'arrows-move';
		$set['content']     = 'newspaper';
		$set['spider']      = 'robot';
		$set['access']      = 'key';
		$set['design']      = 'fan';
		$set['main']        = 'card-list';
		$set['sort']        = 'sort-numeric-down';
		$set['plus']        = 'plus';
		$set['export']      = 'file-arrow-down';
		$set['import']      = 'file-arrow-up';
		$set['simple']      = 'list';
		$set['tile']        = 'layout-split';
		$set['save_exit']   = 'box-arrow-down';
		$set['save']        = 'save';
		$set['preview']     = 'binoculars';
		$set['reply']       = 'reply';
		$set['edit']        = 'pencil-square';
		$set['undo']        = 'backspace';
		$set['remove']      = 'trash';
		$set['close']       = 'x-lg';
		$set['submit']      = 'send';
		$set['bold']        = 'type-bold';
		$set['italic']      = 'type-italic';
		$set['youtube']     = 'youtube';
		$set['image']       = 'image';
		$set['link']        = 'link';
		$set['code']        = 'code';
		$set['quote']       = 'quote';
		$set['category']    = 'tablet-landscape';
		$set['date']        = 'clock';
		$set['user']        = 'person-fill';
		$set['views']       = 'eye';
		$set['replies']     = 'chat-text';
		$set['tag']         = 'tag';
		$set['users']       = 'people-fill';
		$set['copyright']   = 'at';
		$set['redirect']    = 'arrow-return-right';
		$set['calendar']    = 'calendar-plus';
		$set['map_signs']   = 'map';
		$set['arrow_right'] = 'arrow-right';
		$set['arrow_left']  = 'arrow-left';
		$set['donate']      = 'currency-dollar';
		$set['download']    = 'download';
		$set['search']      = 'search';
		$set['toggle']      = 'toggle-';
		$set['gear']        = 'gear-fill';

		$set = array_map(fn($icon): string => $this->prefix . $icon, $set);
	}

	public function credits(array &$links)
	{
		$links[] = [
			'title' => 'Bootstrap Icons',
			'link' => 'https://github.com/twbs/icons',
			'author' => 'The Bootstrap Authors',
			'license' => [
				'name' => 'the MIT License',
				'link' => 'https://github.com/twbs/icons/blob/main/LICENSE.md'
			]
		];
	}
}
