<?php

/**
 * BootstrapIcons.php
 *
 * @package BootstrapIcons (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021-2022 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category addon
 * @version 06.01.22
 */

namespace Bugo\LightPortal\Addons\BootstrapIcons;

use Bugo\LightPortal\Addons\Plugin;

/**
 * Generated by Plugin Maker
 */
class BootstrapIcons extends Plugin
{
	public string $type = 'other';

	public function init()
	{
		loadCSSFile('https://cdn.jsdelivr.net/npm/bootstrap-icons@1/font/bootstrap-icons.min.css', ['external' => true, 'seed' => false]);
	}

	public function prepareIconList(array &$all_icons)
	{
		if (($icons = $this->cache()->get('all_bi_icons', LP_CACHE_TIME * 7)) === null) {
			$content = file_get_contents('https://raw.githubusercontent.com/twbs/icons/main/font/bootstrap-icons.json');
			$json = array_flip(json_decode($content, true));

			$icons = [];
			foreach ($json as $icon) {
				$icons[] = 'bi bi-' . $icon;
			}

			$this->cache()->put('all_bi_icons', $icons, LP_CACHE_TIME * 7);
		}

		$all_icons = array_merge($all_icons, $icons);
	}

	public function credits(array &$links)
	{
		$links[] = [
			'title' => 'Bootstrap Icons',
			'link' => 'https://github.com/twbs/icons',
			'author' => 'The Bootstrap Authors',
			'license' => [
				'name' => 'the MIT License',
				'link' => 'https://github.com/twbs/icons/blob/main/LICENSE.md'
			]
		];
	}
}
