<?php

/**
 * BootstrapIcons
 *
 * @package Light Portal
 * @link https://github.com/dragomano/Light-Portal
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @version 1.9
 */

namespace Bugo\LightPortal\Addons\BootstrapIcons;

use Bugo\LightPortal\Addons\Plugin;
use Bugo\LightPortal\Helpers;

/**
 * Generated by Plugin Maker
 */
class BootstrapIcons extends Plugin
{
	/** @var string */
	public $type = 'other';

	/**
	 * @return void
	 */
	public function init()
	{
		loadCSSFile('https://cdn.jsdelivr.net/npm/bootstrap-icons@1/font/bootstrap-icons.min.css', array('external' => true, 'seed' => false));
	}

	/**
	 * @param string $template
	 * @param string $icon
	 * @return void
	 */
	public function prepareIconTemplate(string &$template, string $icon)
	{
		$template = '<i class="bi bi-' . $icon . '"></i> ';
	}

	/**
	 * @param array $all_icons
	 * @param string $template
	 * @return void
	 */
	public function prepareIconList(array &$all_icons, string &$template)
	{
		$content = file_get_contents('https://raw.githubusercontent.com/twbs/icons/main/font/bootstrap-icons.json');
		$icons = json_decode($content);

		if (!empty($icons)) {
			foreach ($icons as $icon => $id) {
				$all_icons[] = $icon;
			}
		}

		$template = '<i class="bi bi-%1$s"></i>&nbsp;%1$s';
	}

	/**
	 * @param array $links
	 * @return void
	 */
	public function credits(array &$links)
	{
		$links[] = array(
			'title' => 'Bootstrap Icons',
			'link' => 'https://github.com/twbs/icons',
			'author' => 'The Bootstrap Authors',
			'license' => array(
				'name' => 'the MIT License',
				'link' => 'https://github.com/twbs/icons/blob/main/LICENSE.md'
			)
		);
	}
}
