<?php declare(strict_types=1);

/**
 * @package Calculator (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023-2025 Bugo
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @category plugin
 * @version 17.10.25
 */

namespace LightPortal\Plugins\Calculator;

use LightPortal\Plugins\Block;
use LightPortal\Plugins\Event;
use LightPortal\Plugins\PluginAttribute;
use LightPortal\Utils\Traits\HasView;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
#[PluginAttribute(icon: 'fas fa-calculator', showContentClass: false)]
class Calculator extends Block
{
	use HasView;

	public function prepareContent(Event $e): void
	{
		echo $this->view(params: ['id' => $e->args->id]);
	}
}
