<?php declare(strict_types=1);

/**
 * @package MaterialDesignIcons (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023-2024 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category plugin
 * @version 22.12.24
 */

namespace Bugo\LightPortal\Plugins\MaterialDesignIcons;

use Bugo\Compat\Theme;
use Bugo\LightPortal\Plugins\Event;
use Bugo\LightPortal\Plugins\Plugin;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class MaterialDesignIcons extends Plugin
{
	public string $type = 'icons';

	private string $prefix = 'mdi mdi-';

	public function init(): void
	{
		Theme::loadCSSFile(
			'https://cdn.jsdelivr.net/npm/@mdi/font@7/css/materialdesignicons.min.css',
			[
				'external' => true,
				'seed'     => false,
			]
		);
	}

	public function prepareIconList(Event $e): void
	{
		$cacheTTL = 30 * 24 * 60 * 60;

		if (($mdIcons = $this->cache()->get('all_md_icons', $cacheTTL)) === null) {
			$content = file_get_contents('https://raw.githubusercontent.com/Templarian/MaterialDesign/master/meta.json');
			$json = json_decode($content);

			$mdIcons = [];
			foreach ($json as $icon) {
				$mdIcons[] = $this->prefix . $icon->name;
			}

			$this->cache()->put('all_md_icons', $mdIcons, $cacheTTL);
		}

		$e->args->icons = array_merge($e->args->icons, $mdIcons);
	}

	public function credits(Event $e): void
	{
		$e->args->links[] = [
			'title' => 'Material Design Icons',
			'link' => 'https://pictogrammers.com/library/mdi/',
			'author' => 'Pictogrammers',
			'license' => [
				'name' => 'Pictogrammers Free License',
				'link' => 'https://pictogrammers.com/docs/general/license/'
			]
		];
	}
}
