<?php

/**
 * SimpleChat.php
 *
 * @package SimpleChat (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023 Bugo
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @category addon
 * @version 06.12.23
 */

namespace Bugo\LightPortal\Addons\SimpleChat;

use Bugo\LightPortal\Addons\Block;
use Bugo\LightPortal\Areas\Fields\CheckboxField;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class SimpleChat extends Block
{
	public string $icon = 'fas fa-message';

	private Chat $chat;

	public function __construct()
	{
		$this->chat = new Chat;
	}

	public function init(): void
	{
		$this->applyHook('actions');
	}

	public function actions(): void
	{
		if ($this->request()->isNot('portal'))
			return;

		if ($this->request()->has('chat') && $this->request('chat') === 'post') {
			$this->chat->addMessage();
		}

		if ($this->request()->has('chat') && $this->request('chat') === 'update') {
			$this->chat->deleteMessage();
		}
	}

	public function addSettings(): void
	{
		$this->prepareTable();
	}

	public function blockOptions(array &$options): void
	{
		$options['simple_chat']['parameters'] = [
			'show_avatars' => false,
		];
	}

	public function validateBlockData(array &$parameters, string $type): void
	{
		if ($type !== 'simple_chat')
			return;

		$parameters['show_avatars'] = FILTER_VALIDATE_BOOLEAN;
	}

	public function prepareBlockFields(): void
	{
		if ($this->context['lp_block']['type'] !== 'simple_chat')
			return;

		CheckboxField::make('show_avatars', $this->txt['lp_simple_chat']['show_avatars'])
			->setTab('appearance')
			->setValue($this->context['lp_block']['options']['parameters']['show_avatars']);
	}

	public function getData(int $block_id, array $parameters): array
	{
		$messages = $this->chat->getMessages($block_id);

		if ($parameters['show_avatars'])
			$messages = $this->getItemsWithUserAvatars($messages);

		return $messages;
	}

	public function prepareContent($data, array $parameters): void
	{
		if ($data->type !== 'simple_chat')
			return;

		$this->loadCssFile('admin.css');
		$this->loadJavaScriptFile('light_portal/bundle.min.js', ['defer' => true]);

		$parameters['show_avatars'] ??= false;

		$messages = $this->cache('simple_chat_addon_b' . $data->block_id)
			->setLifeTime($data->cache_time)
			->setFallback(self::class, 'getData', $data->block_id, $parameters);

		$this->context['lp_chats'][$data->block_id] = json_encode($messages, JSON_UNESCAPED_UNICODE);

		$this->setTemplate();

		show_chat_block($data->block_id, (bool) $parameters['show_avatars'], $this->isInSidebar($data->block_id));
	}

	public function onBlockRemoving(array $items): void
	{
		$this->smcFunc['db_query']('', '
			DELETE FROM {db_prefix}lp_simple_chat_messages
			WHERE block_id IN ({array_int:items})',
			[
				'items' => $items,
			]
		);
	}

	private function prepareTable(): void
	{
		$tables = [];

		$this->dbExtend('packages');

		if (! empty($this->smcFunc['db_list_tables'](false, $this->db_prefix . 'lp_simple_chat_messages')))
			return;

		$tables[] = [
			'name' => 'lp_simple_chat_messages',
			'columns' => [
				[
					'name'     => 'id',
					'type'     => 'int',
					'size'     => 10,
					'unsigned' => true,
					'auto'     => true
				],
				[
					'name'     => 'block_id',
					'type'     => 'int',
					'size'     => 10,
					'unsigned' => true
				],
				[
					'name'     => 'user_id',
					'type'     => 'int',
					'size'     => 10,
					'unsigned' => true
				],
				[
					'name' => 'message',
					'type' => 'varchar',
					'size' => 255,
					'null' => false
				],
				[
					'name'     => 'created_at',
					'type'     => 'int',
					'size'     => 10,
					'unsigned' => true,
					'default'  => 0
				]
			],
			'indexes' => [
				[
					'type'    => 'primary',
					'columns' => ['id']
				]
			]
		];

		foreach ($tables as $table) {
			$this->smcFunc['db_create_table']('{db_prefix}' . $table['name'], $table['columns'], $table['indexes']);
		}
	}
}
