<?php

return [
	'description' => 'Interactive tutorial to get acquainted with the portal features.<br>Once enabled, look for the "Interactive tour" button on the portal admin areas.',
	'tour_button' => 'Interactive tour',
	'theme' => 'Theme',
	'theme_set' => ['Classic', 'Dark', 'Modern', 'Flattener'],
	'show_progress' => 'Show introduction progress',
	'show_buttons' => 'Show introduction navigation buttons',
	'exit_on_overlay_click' => 'Exit introduction when clicking on overlay layer',
	'keyboard_navigation' => 'Navigating with keyboard',
	'disable_interaction' => 'Disable interactions with elements inside the highlighted box',
	'basic_settings_tour' => [
		'This page contains the basic portal settings.',
		'Here you can change the front page of the portal.',
		'Let the most popular articles be displayed first!',
		'Or maybe you want to direct the front page to a custom CMS?',
		'Do not forget to configure permissions.',
		'Use this button to get a list of all portal settings stored in the database.',
		'Do not forget to ask questions or at least thank the developer.',
	],
	'extra_settings_tour' => [
		'Here you can change the general settings of the portal pages and blocks.',
		'And here - configure the loading of the FontAwesome icon library.',
	],
	'categories_tour' => [
		'If you cannot live without categories, add them here.',
		'Added categories are displayed here. They can be edited and dragged, changing the order.',
	],
	'panels_tour' => [
		'A mini version of the portal layout.',
		'Each panel can be customized by specifying the desired width for different screen resolutions.',
		'Opposite panels can also be interchanged.',
		'The direction of blocks in the panels is also adjustable.',
	],
	'misc_tour' => [
		'When developing templates or plugins, you may find debugging information useful.',
		'Want to try combining Light Portal with other portals? Set the appropriate parameters.',
		'Do not forget to optimize portal tables!',
	],
	'blocks_tour' => [
		'This is the control room of all the portal blocks. If you create more than 100 blocks, be sure to share a screenshot!',
		'This is the name of the panel. The number of blocks placed on this panel is shown in brackets.',
		'Each row in this table represents a corresponding block.',
		'The block can be enabled or disabled at the touch of a button.',
		'You can also clone (make a copy of), edit or delete a block.',
		'Also, the blocks are easy to swap out. Try it!',
	],
	'pages_tour' => [
		'This is the control room of all portal pages.',
		'Each line in this table represents a corresponding page.',
		'Date - generalized field for the date of page creation and the date of page updating.',
		'You want to know how many times this or that page has been viewed, do not you?',
		'Page alias is a part of page after %s in address bar',
		'Status is status! Turn pages on or off with a single tap.',
		'In the additional actions, editing and deleting pages are hidden.',
		'When it gets to be a lot of pages, a search will come in handy!',
	],
	'plugins_tour' => [
		'This page lists all installed portal addons in alphabetical order.',
		'You can filter addons by type.',
		'Each addon has a name, type, and description.',
		'Some addons have settings. Click on the gear to see them.',
		'To enable or disable the addon, click this button.',
	],
	'add_plugins_tour' => [
		'Which is more interesting - to study ready-made plugins or to make your own?',
		'Whatever you call the ship, that is how it sails. Does this apply to plugins? Who knows....',
		'No way to make a plugin without a type. Like a ship without an anchor.',
		'The description should be clear to anyone (even to a hedgehog).',
		'No way to make a plugin without a census. The world needs to know its heroes!',
		'If your plugin cannot work without settings, take a look here.',
		'Lastly, a little bit of paperwork. Well, where would not it be?',
	],
];
