<?php

/**
 * ExtendedMetaTags.php
 *
 * @package ExtendedMetaTags (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021-2022 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category addon
 * @version 31.12.21
 */

namespace Bugo\LightPortal\Addons\ExtendedMetaTags;

use Bugo\LightPortal\Addons\Plugin;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class ExtendedMetaTags extends Plugin
{
	public string $type = 'page_options';

	private array $meta_robots = ['', 'index, follow', 'index, nofollow', 'noindex, follow', 'noindex, nofollow'];
	private array $meta_rating = ['', '14 years', 'adult', 'general', 'mature', 'restricted', 'save for kids'];

	public function init()
	{
		add_integration_function('integrate_theme_context', __CLASS__ . '::themeContext#', false, __FILE__);
	}

	public function themeContext()
	{
		if ($this->request()->has('page') === false || empty($this->context['lp_page']['options']))
			return;

		if (! empty($this->context['lp_page']['options']['meta_robots'])) {
			$this->context['meta_tags'][] = ['name' => 'robots', 'content' => $this->context['lp_page']['options']['meta_robots']];
		}

		if (! empty($this->context['lp_page']['options']['meta_rating'])) {
			$this->context['meta_tags'][] = ['name' => 'rating', 'content' => $this->context['lp_page']['options']['meta_rating']];
		}
	}

	public function pageOptions(array &$options)
	{
		$options['meta_robots'] = '';
		$options['meta_rating'] = '';
	}

	public function validatePageData(array &$parameters)
	{
		$parameters += [
			'meta_robots' => FILTER_SANITIZE_STRING,
			'meta_rating' => FILTER_SANITIZE_STRING,
		];
	}

	public function preparePageFields()
	{
		// Meta robots
		$this->context['posting_fields']['meta_robots']['label']['text'] = $this->txt['lp_extended_meta_tags']['meta_robots'];
		$this->context['posting_fields']['meta_robots']['input'] = [
			'type' => 'select',
			'tab'  => 'seo'
		];

		$robots_variants = array_combine($this->meta_robots, $this->txt['lp_extended_meta_tags']['meta_robots_set']);

		foreach ($robots_variants as $value => $title) {
			$this->context['posting_fields']['meta_robots']['input']['options'][$title] = [
				'value'    => $value,
				'selected' => $value == $this->context['lp_page']['options']['meta_robots']
			];
		}

		addInlineJavaScript('
		new SlimSelect({
			select: "#meta_robots",
			showSearch: false,
			hideSelectedOption: true,
			closeOnSelect: true,
			showContent: "down"
		});', true);

		// Meta rating
		$this->context['posting_fields']['meta_rating']['label']['text'] = $this->txt['lp_extended_meta_tags']['meta_rating'];
		$this->context['posting_fields']['meta_rating']['input'] = [
			'type' => 'select',
			'tab'  => 'seo'
		];

		$rating_variants = array_combine($this->meta_rating, $this->txt['lp_extended_meta_tags']['meta_rating_set']);

		foreach ($rating_variants as $value => $title) {
			$this->context['posting_fields']['meta_rating']['input']['options'][$title] = [
				'value'    => $value,
				'selected' => $value == $this->context['lp_page']['options']['meta_rating']
			];
		}

		addInlineJavaScript('
		new SlimSelect({
			select: "#meta_rating",
			showSearch: false,
			hideSelectedOption: true,
			closeOnSelect: true,
			showContent: "down"
		});', true);
	}
}
