<?php declare(strict_types=1);

/**
 * @package SimpleChat (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023-2025 Bugo
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @category plugin
 * @version 07.08.25
 */

namespace Bugo\LightPortal\Plugins\SimpleChat;

use Bugo\Compat\Db;
use Bugo\Compat\Theme;
use Bugo\Compat\Utils;
use Bugo\LightPortal\Enums\Tab;
use Bugo\LightPortal\Plugins\Block;
use Bugo\LightPortal\Plugins\Event;
use Bugo\LightPortal\UI\Fields\CheckboxField;
use Bugo\LightPortal\UI\Fields\NumberField;
use Bugo\LightPortal\UI\Fields\RadioField;
use Bugo\LightPortal\Utils\ParamWrapper;

use function array_combine;
use function json_encode;
use function show_chat_block;

use const FILTER_DEFAULT;
use const FILTER_VALIDATE_BOOLEAN;
use const JSON_UNESCAPED_UNICODE;

if (! defined('LP_NAME'))
	die('No direct access...');

/**
 * Generated by PluginMaker
 */
class SimpleChat extends Block
{
	public string $icon = 'fas fa-message';

	private array $defaultParams = [
		'show_avatars'     => false,
		'form_position'    => 'bottom',
		'window_height'    => 100,
		'refresh_interval' => 2,
	];

	private readonly Chat $chat;

	public function __construct()
	{
		parent::__construct();

		$this->chat = new Chat($this->name);
	}

	public function addSettings(): void
	{
		$this->chat->prepareTable();
	}

	public function prepareBlockParams(Event $e): void
	{
		$e->args->params = $this->defaultParams;
	}

	public function validateBlockParams(Event $e): void
	{
		$e->args->params = [
			'show_avatars'     => FILTER_VALIDATE_BOOLEAN,
			'form_position'    => FILTER_DEFAULT,
			'window_height'    => FILTER_VALIDATE_INT,
			'refresh_interval' => FILTER_VALIDATE_INT,
		];
	}

	public function prepareBlockFields(Event $e): void
	{
		$options = $e->args->options;

		CheckboxField::make('show_avatars', $this->txt['show_avatars'])
			->setTab(Tab::APPEARANCE)
			->setValue($options['show_avatars']);

		RadioField::make('form_position', $this->txt['form_position'])
			->setOptions(array_combine(['bottom', 'top'], $this->txt['form_position_set']))
			->setValue($options['form_position']);

		NumberField::make('window_height', $this->txt['window_height'])
			->setAttribute('step', 10)
			->setAttribute('min', 0)
			->setValue($options['window_height']);

		NumberField::make('refresh_interval', $this->txt['refresh_interval'])
			->setAttribute('min', 0)
			->setValue($options['refresh_interval']);
	}

	public function prepareContent(Event $e): void
	{
		$this->loadDependencies();

		[$id, $parameters] = [$e->args->id, $e->args->parameters];

		$parameters = $this->mergeWithDefaultParams($parameters);

		$this->chat->setInSidebar($this->isInSidebar($id));
		$this->chat->setParameters($parameters);

		$messages = $this->getCachedMessages($id, $e->args->cacheTime);

		Utils::$context['lp_chats'][$id] = json_encode($messages, JSON_UNESCAPED_UNICODE);

		$this->useTemplate();

		$this->handleChatRequests($id, $messages);
		$this->renderChatBlock($id, $parameters);
	}

	public function onBlockRemoving(Event $e): void
	{
		Db::$db->query('
			DELETE FROM {db_prefix}lp_simple_chat_messages
			WHERE block_id IN ({array_int:items})',
			[
				'items' => $e->args->items,
			]
		);
	}

	private function loadDependencies(): void
	{
		Theme::loadCSSFile('admin.css');
		Theme::loadJavaScriptFile(
			'https://cdn.jsdelivr.net/npm/htmx.org@2/dist/htmx.min.js',
			[
				'defer'    => true,
				'external' => true,
			]
		);
	}

	private function mergeWithDefaultParams(ParamWrapper $parameters): ParamWrapper
	{
		foreach ($this->defaultParams as $key => $value) {
			$parameters[$key] ??= $value;
		}

		return $parameters;
	}

	private function getCachedMessages(int $id, int $cacheTime): array
	{
		return $this->cache($this->name . '_addon_b' . $id)
			->setLifeTime($cacheTime)
			->setFallback(fn() => $this->chat->getMessages($id));
	}

	private function handleChatRequests(int $id, array $messages): void
	{
		if ($this->request()->isNot('portal')) {
			return;
		}

		if ($this->request()->has('chat')) {
			$action = $this->request()->get('chat');

			if ($action === 'add_message') {
				$this->chat->addMessage();
			} elseif ($action === 'remove_message') {
				$this->chat->deleteMessage();
			} else {
				$this->chat->renderMessages($messages, $id);
			}
		}
	}

	private function renderChatBlock(int $id, ParamWrapper $parameters): void
	{
		show_chat_block($id, $parameters, $this->isInSidebar($id));
	}
}
