<?php
// Spanish translation by Rock Lee https://www.bombercode.net | Rev. 1.0

return [
	'title' => 'Control deslizante de imagen',
	'description' => 'Pequeño control deslizante para todos los propósitos.',
	'axis' => 'El eje del control deslizante',
	'num_items' => 'Número de diapositivas que se muestran en la ventana gráfica',
	'num_items_subtext' => 'Si las diapositivas son menores o iguales que los elementos, el control deslizante no se inicializará.',
	'gutter' => 'Espacio entre diapositivas (en píxeles)',
	'edge_padding' => 'Espacio en el exterior (en píxeles)',
	'controls' => 'Mostrar botones anterior/siguiente',
	'controls_buttons' => array('Previo', 'Próximo'),
	'nav' => 'Mostrar componentes de navegación (puntos)',
	'nav_as_thumbnails' => 'Mostrar miniaturas en lugar de puntos',
	'arrow_keys' => 'Usa las teclas de flecha para cambiar de diapositiva',
	'fixed_width' => 'Ancho de deslizamiento fijo',
	'auto_width' => 'Ancho automático de cada diapositiva',
	'auto_height' => 'La altura del contenedor del control deslizante cambia según la altura de cada diapositiva',
	'slide_by' => 'Número de diapositivas que van con un "clic"',
	'speed' => 'Velocidad de transición ​​entre diapositivas (en milisegundos) ',
	'autoplay' => 'Reproducción automática del control deslizante',
	'autoplay_timeout' => 'Cambio de tiempo entre 2 diapositivas de reproducción automática (en milisegundos)',
	'autoplay_direction' => 'Dirección del movimiento de la diapositiva (ascendente/descendente del índice de la diapositiva)',
	'autoplay_direction_set' => array('Hacia adelante', 'Hacia atrás'),
	'loop' => 'Muévete por todas las diapositivas sin problemas',
	'rewind' => 'Moverse al borde opuesto al llegar a la primera o última diapositiva',
	'mouse_drag' => 'Cambio de diapositivas arrastrándolas',
	'lazyload' => 'Activa la carga diferida de imágenes que no se ven actualmente, ahorrando así ancho de banda',
	'images' => 'Lista de imágenes',
	'title_placeholder' => 'Título (opcional)',
	'link_placeholder' => 'Enlace de la imágen',
	'image_add' => 'Agregar nueva imagen',
];
