<?php

return [
	'description' => 'A tool for creating plugin skeletons. Adds an "Add Plugin" page to the plugin manage area.',
	'add' => 'Add plugin',
	'add_title' => 'Adding a plugin',
	'add_desc' => 'The plugin maker wizard will help you prepare the addon skeleton for further changes. Fill in the suggested fields carefully.',
	'add_info' => 'The plugin files will be saved in the directory %1$s<br>Be sure to look there and check/edit the necessary files.',
	'tab_content' => 'Basic information',
	'tab_copyrights' => 'Copyrights',
	'tab_settings' => 'Settings',
	'tab_tuning' => 'Additional',
	'name' => 'The plugin name',
	'name_subtext' => 'In Latin letters, without spaces!',
	'type' => 'The plugin type',
	'site_subtext' => 'Website where users can download new versions of this plugin.',
	'license' => 'The plugin license',
	'license_own' => 'Own license',
	'license_name' => 'The license name',
	'license_link' => 'The license link',
	'use_smf_hooks' => 'Will you use SMF hooks?',
	'use_components' => 'Will you use third-party scripts with licenses?',
	'requires_placeholder' => 'If your plugin depends on others, select them',
	'disables_placeholder' => 'If your plugin replaces others, select them',
	'component_name' => 'Component name',
	'component_link' => 'Link to component site',
	'component_author' => 'Component author',
	'option_name' => 'Option name (Latin)',
	'option_type' => 'Option type',
	'option_type_set' => array('Text field', 'Web address', 'Input color', 'Input number (int)', 'Input number (float)', 'Checkbox', 'Multiple select', 'Select'),
	'option_default_value' => 'Default value',
	'option_variants' => 'Possible values',
	'option_variants_placeholder' => 'Multiple options separated by "|"',
	'option_translations' => 'Localization',
	'option_new' => 'Add option',
	'no_valid_name' => 'The specified name does not match the rules!',
	'no_unique_name' => 'A plugin with this name already exists!',
	'no_description' => 'The description not specified! It is required.',
	'addon_dir_not_writable' => 'The <strong>%1$s</strong> directory must be writable!',
	'addon_dir_not_created' => 'The plugin directory was not created!',
	'lang_dir_not_created' => 'The plugin\'s lang directory was not created!',
];
