<?php

/**
 * PageLikes.php
 *
 * @package PageLikes (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2021-2022 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category addon
 * @version 31.12.21
 */

namespace Bugo\LightPortal\Addons\PageLikes;

use Bugo\LightPortal\Addons\Plugin;
use Likes;

/**
 * Generated by PluginMaker
 */
class PageLikes extends Plugin
{
	public string $type = 'other';

	public function init()
	{
		add_integration_function('integrate_valid_likes', __CLASS__ . '::validLikes#', false, __FILE__);
		add_integration_function('integrate_issue_like', __CLASS__ . '::issueLike#', false, __FILE__);
	}

	public function validLikes(string $type, int $content)
	{
		if ($type !== 'lpp')
			return false;

		$request = $this->smcFunc['db_query']('', '
			SELECT alias, author_id
			FROM {db_prefix}lp_pages
			WHERE page_id = {int:id}
			LIMIT 1',
			[
				'id' => $content
			]
		);

		[$alias, $author_id] = $this->smcFunc['db_fetch_row']($request);

		$this->smcFunc['db_free_result']($request);
		$this->context['lp_num_queries']++;

		if (empty($alias))
			return false;

		return [
			'type'        => $type,
			'flush_cache' => 'lp_likes_page_' . $content . '_' . $this->user_info['id'],
			'redirect'    => LP_PAGE_PARAM . '=' . $alias,
			'can_like'    => $this->user_info['id'] == $author_id ? 'cannot_like_content' : (allowedTo('likes_like') ? true : 'cannot_like_content')
		];
	}

	public function issueLike(Likes $obj)
	{
		if ($obj->get('type') !== 'lpp')
			return;

		$this->cache()->put('likes_page_' . $obj->get('content') . '_count', ['num_likes' => $obj->get('numLikes')]);
	}

	public function preparePageData(array &$data, bool $is_author)
	{
		if (empty($this->modSettings['enable_likes']))
			return;

		loadJavaScriptFile('topic.js', ['defer' => false, 'minimize' => true], 'smf_topic');

		$user_likes = $this->user_info['is_guest'] ? [] : $this->prepareLikesContext($data['id']);

		$data['likes'] = [
			'count'    => $this->getLikesCount($data['id']),
			'you'      => in_array($data['id'], $user_likes),
			'can_like' => ! $this->user_info['is_guest'] && ! $is_author && allowedTo('likes_like')
		];

		ob_start();

		$this->loadTemplate();

		show_likes_block($data);

		$data['addons'] .= ob_get_clean();
	}

	private function prepareLikesContext(int $page): array
	{
		if (empty($page))
			return [];

		$cache_key = 'likes_page_' . $page . '_' . $this->user_info['id'];

		if (($liked_pages = $this->cache()->get($cache_key)) === null) {
			$request = $this->smcFunc['db_query']('', '
				SELECT content_id
				FROM {db_prefix}user_likes AS l
					INNER JOIN {db_prefix}lp_pages AS p ON (l.content_id = p.page_id)
				WHERE l.id_member = {int:current_user}
					AND l.content_type = {literal:lpp}
					AND p.page_id = {int:page}',
				[
					'current_user' => $this->user_info['id'],
					'page'         => $page
				]
			);

			$liked_pages = [];
			while ($row = $this->smcFunc['db_fetch_assoc']($request))
				$liked_pages[] = (int) $row['content_id'];

			$this->smcFunc['db_free_result']($request);
			$this->context['lp_num_queries']++;

			$this->cache()->put($cache_key, $liked_pages);
		}

		return $liked_pages;
	}

	private function getLikesCount(int $page): int
	{
		if (empty($page))
			return 0;

		$cache_key = 'likes_page_' . $page . '_count';

		if (($num_likes = $this->cache()->get($cache_key)) === null) {
			$request = $this->smcFunc['db_query']('', '
				SELECT COUNT(content_id)
				FROM {db_prefix}user_likes AS l
					INNER JOIN {db_prefix}lp_pages AS p ON (l.content_id = p.page_id)
				WHERE l.content_type = {literal:lpp}
					AND p.page_id = {int:page}',
				[
					'page' => $page
				]
			);

			[$num_likes] = $this->smcFunc['db_fetch_row']($request);

			$this->smcFunc['db_free_result']($request);
			$this->context['lp_num_queries']++;

			$this->cache()->put($cache_key, ['num_likes' => $num_likes]);
		}

		return is_array($num_likes) ? $num_likes['num_likes'] : (int) $num_likes;
	}
}
