<?php

/**
 * FontAwesome6
 *
 * @package FontAwesome6 (Light Portal)
 * @link https://custom.simplemachines.org/index.php?mod=4244
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2022 Bugo
 * @license https://spdx.org/licenses/GPL-3.0-or-later.html GPL-3.0-or-later
 *
 * @category addon
 * @version 09.01.22
 */

namespace Bugo\LightPortal\Addons\FontAwesome6;

use Bugo\LightPortal\Addons\Plugin;

/**
 * Generated by Plugin Maker
 */
class FontAwesome6 extends Plugin
{
	public string $type = 'other';

	private string $prefix = 'fa-solid fa-';

	public function addSettings(array &$config_vars)
	{
		$config_vars['font_awesome6'][] = ['check', 'replace_ui_icons'];
	}

	public function prepareIconList(array &$all_icons)
	{
		if (($icons = $this->cache()->get('all_fa6icons', LP_CACHE_TIME * 7)) === null) {
			$content = file_get_contents('https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/metadata/icons.json');
			$json = json_decode($content);

			if (empty($json))
				return [];

			$icons = [];
			foreach ($json as $icon => $value) {
				foreach ($value->styles as $style) {
					$icons[] = 'fa-' . $style . ' fa-' . $icon;
				}
			}

			$this->cache()->put('all_fa6icons', $icons, LP_CACHE_TIME * 7);
		}

		$all_icons = array_merge($all_icons, $icons);
	}

	public function changeIconSet(array &$set)
	{
		if (empty($this->modSettings['lp_font_awesome6_addon_replace_ui_icons']))
			return;

		$set['home']        = 'house';
		$set['cog_spin']    = 'cog fa-spin';
		$set['pager']       = 'pager';
		$set['sections']    = 'folder';
		$set['panels']      = 'table-columns';
		$set['tools']       = 'sliders';
		$set['info']        = 'circle-info fa-beat-fade';
		$set['arrows']      = 'up-down-left-right';
		$set['content']     = 'newspaper fa-2x';
		$set['spider']      = 'spider';
		$set['access']      = 'universal-access';
		$set['design']      = 'object-group';
		$set['main']        = 'table-list';
		$set['sort']        = 'sort';
		$set['plus']        = 'plus';
		$set['export']      = 'file-export';
		$set['import']      = 'file-import';
		$set['simple']      = 'bars fa-2x';
		$set['tile']        = 'table-cells-large fa-2x';
		$set['save_exit']   = 'door-open';
		$set['save']        = 'floppy-disk';
		$set['preview']     = 'square-check';
		$set['reply']       = 'reply';
		$set['edit']        = 'pen-to-square';
		$set['undo']        = 'rotate-left';
		$set['remove']      = 'trash';
		$set['close']       = 'xmark';
		$set['submit']      = 'paper-plane';
		$set['bold']        = 'bold';
		$set['italic']      = 'italic';
		$set['image']       = 'image';
		$set['link']        = 'link';
		$set['code']        = 'code';
		$set['quote']       = 'quote-right';
		$set['category']    = 'rectangle-list';
		$set['date']        = 'clock';
		$set['user']        = 'user';
		$set['views']       = 'eye';
		$set['replies']     = 'comment';
		$set['tag']         = 'tag';
		$set['users']       = 'users';
		$set['copyright']   = 'copyright';
		$set['redirect']    = 'diamond-turn-right';
		$set['calendar']    = 'calendar';
		$set['map_signs']   = 'signs-post';
		$set['arrow_right'] = 'arrow-right-long';
		$set['arrow_left']  = 'arrow-left-long';
		$set['donate']      = 'circle-dollar-to-slot fa-3x';
		$set['download']    = 'download fa-3x';
		$set['search']      = 'magnifying-glass';
		$set['toggle']      = '3x fa-toggle-';
		$set['gear']        = '2x fa-gear';

		$set = array_map(fn($icon): string => $this->prefix . $icon, $set);

		$set['youtube'] = 'fa-brands fa-youtube';
	}

	public function credits(array &$links)
	{
		$links[] = array(
			'title' => 'Font Awesome 6 Free',
			'link' => 'https://fontawesome.com/v6.0/icons',
			'author' => 'Fonticons, Inc.',
			'license' => array(
				'name' => 'the Font Awesome Free License',
				'link' => 'https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt'
			)
		);
	}
}
