# .github/workflows/crowdin.yml

name: Crowdin Action

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Themes/default/languages/**'
      - 'src/Sources/LightPortal/Plugins/**'
      - 'docs/.vitepress/locales/**'
      - 'docs/src/**'

env:
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: env.CROWDIN_API_TOKEN != null
        uses: actions/checkout@v4

      - name: Crowdin Action
        if: env.CROWDIN_API_TOKEN != null
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          #crowdin_branch_name: 'next'
          config: '.github/crowdin.yml'
